### ISSUE TITLE
"used in model" NPE with white orbits

### ISSUE THREAD

**Issue by vorth** [vZome/vzome#2]
_From @vorth on October 18, 2015 20:25_

In some circumstances, showing "used in model" orbits will throw repeated NPEs if there are several unknown orbits used in the model.

I was applying some odd linear maps (6 strut form).

java.lang.NullPointerException
    at org.vorthmann.zome.ui.LengthDialog.<init>(LengthDialog.java:42)
    at org.vorthmann.zome.ui.NewLengthPanel.setController(NewLengthPanel.java:84)
    at org.vorthmann.zome.ui.StrutBuilderPanel.changeOrbit(StrutBuilderPanel.java:142)
    at org.vorthmann.zome.ui.StrutBuilderPanel.access$0(StrutBuilderPanel.java:135)
    at org.vorthmann.zome.ui.StrutBuilderPanel$3.propertyChange(StrutBuilderPanel.java:108)
    at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
    at org.vorthmann.zome.app.impl.OrbitSetController.recalculateDots(OrbitSetController.java:121)
    at org.vorthmann.zome.app.impl.OrbitSetController.doAction(OrbitSetController.java:128)

_Copied from original issue: vZome/vzome-desktop#16_

**Comment by vorth** [comment]
Git commit for that stack trace is d2b1e2b49ad0dfd155980911402b9e0a25402f60, though not pushed to origin yet.  Prior commit, which is pushed, is e1b1e520e918c1d0854c667c61c407f6383fa18f
